version: '3.9'
services:
  postgres:
    image: postgres:14.2-alpine
    environment:
      POSTGRES_DB: 'selina'
      POSTGRES_USER: 'selina_admin'
      POSTGRES_PASSWORD: 'secret_password'
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - ./db/data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
