CREATE TABLE countries (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"name" varchar(255) NOT NULL,
	CONSTRAINT countries_pk PRIMARY KEY (id)
);
INSERT INTO countries(id,name) VALUES(2,'Panama'),(1,'Guatemala'),(3,'Mexico'),(4,'Colombia'),(5,'Nicaragua');

CREATE TABLE cities (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	country_id int4 NOT NULL,
	"name" varchar(255) NOT NULL,
	CONSTRAINT cities_pk PRIMARY KEY (id)
);
ALTER TABLE cities ADD CONSTRAINT cities_countries_fk FOREIGN KEY (country_id) REFERENCES countries(id);
INSERT INTO cities(country_id,name,id) VALUES(1,'Antigua',1),(2,'Bocas Del Toro',2),(3,'Cancun',3),(4,'Cartagena',4),(5,'Granada',5),(3,'Guadalahara',6);

CREATE TABLE room_types (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"name" varchar(255) NOT NULL,
	CONSTRAINT room_types_pk PRIMARY KEY (id)
);
INSERT INTO room_types(id,name) VALUES(1,'Dorm'),(2,'Private'),(3,'Deluxe');

CREATE TABLE bookings (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	city_id int4 NOT NULL,
	room_type_id int4 NOT NULL,
	dates daterange NOT NULL,
	CONSTRAINT bookings_pk PRIMARY KEY (id)
);
ALTER TABLE bookings ADD CONSTRAINT bookings_room_types_fk FOREIGN KEY (room_type_id) REFERENCES room_types(id);
ALTER TABLE bookings ADD CONSTRAINT bookings_cities_fk FOREIGN KEY (city_id) REFERENCES cities(id);
INSERT INTO bookings(id,city_id,room_type_id,dates) VALUES(1,3,2,'[2020-01-01,2030-01-01)');